seed_everything: 42

model:
  class_path: models.AttributeClassifier
  init_args:
    target_attr: "age"
    hidden_dims: [256, 128]
    dropout_rate: 0.1
    lr: 1e-3
    weight_decay: 1e-5
    pred_file: "Adv_strong"
    include_rating: false
    use_identifiers: false
    strict_feature_check: true

# Run flags for this MLP auditor
do_train: true
do_validate: true
do_test: true
do_predict: false
do_attack: false