seed_everything: 0
# Base model config

model:
  class_path: models.BaseModel
  init_args:
    num_users: 480189
    num_items: 17770
    embed_dim: 512
    loss_function: "MSE"
    l2_penalty: 1e-5
    dropout_rate: 0.2
    learning_rate: 2e-4
    enable_dp: false




# Lightning execution flow flags
do_train: true
do_test: true
do_predict: false
do_validate: true  # Important for DP monitoring
do_analyze: true

