seed_everything: 0
# Base model config

model:
  class_path: models.BaseModel
  init_args:
    num_users: 6040          # safe upper bound (train split had 4832)
    num_items: 3952          # full ML-1M item ID range
    num_genders: 2
    num_occupations: 21
    genre_dim: 19
    use_attrs: true                # from genre_onehot shape


    mlp_dims: [128, 64]
    dropout: 0.2
    learning_rate: 1e-3
    l2_penalty: 1e-3
    loss_function: "MSE"
    target_min: 1.0
    target_max: 5.0


# Lightning execution flow flags
do_train: true
do_test: true
do_predict: false
do_validate: true  # Important for DP monitoring
do_analyze: false

