seed_everything: 0

model:
  class_path: models.CustomDP_SGD
  init_args:
    num_users: 304398
    num_items: 17770
    embed_dim: 64
    loss_function: "MSE"  # Good choice, MSE is more stable than RMSE for training
    l2_penalty: 1e-4
    learning_rate: 1e-4
    dropout_rate: 0.3
    noise_scale: 0.7
    clip_norm: 1.0
    delta: 1e-5
    enable_dp: False

# Lightning execution flow flags
do_train: true
do_test: true
do_predict: false
do_validate: true  # Important for DP monitoring
do_analyze: false

