seed_everything: 0

model:
  class_path: models.CustomDP_SGD
  init_args:
    num_users: 480189
    num_items: 17770
    embed_dim: 64
    loss_function: "MSE"
    l2_penalty: 1e-3
    learning_rate: 2e-4
    enable_dp: false  
    noise_scale: 3.23

    # DP parameters

    delta: 1e-5
    dropout_rate: 0.2


# Lightning execution flow flags
do_train: true
do_test: true
do_predict: false
do_validate: true  # Important for DP monitoring
do_analyze: true

