seed_everything: 42

model:
  class_path: models.WGAN
  init_args:
    num_attack_samples: 10000
    noise_dim: 32
    output_dim: 25
    lr: 1e-6
    n_critic: 5
    lambda_gp: 0.5
    pred_file: "cus_mid"  # Name of the prediction file for attack



do_validate: false
do_test: false
do_predict: false
do_attack: false
do_create_synthetic_data: true