seed_everything: 0

model:

  class_path: models.DPFM_GANTrainer  # Update if using custom model class
  init_args:
    num_users: 6040
    num_items: 3706
    num_genders: 2
    num_occupations: 21
    genre_dim: 20
    embed_dim: 64
    learning_rate: 0.001
    loss_function: "Huber"
    l2_penalty: 1e-4
    use_attrs: true
    lr: 0.001
    lambda_adv: 0.1
    enable_dp: true
    target_epsilon: 0.2
    target_delta: 1e-5
    max_grad_norm: 1.0
    loss_type: "huber"
    lambda_gp: 10.0

# Lightning execution flow flags
do_train: true
do_test: true
do_predict: false
do_validate: true  # Important for DP monitoring
do_analyze: false

