seed_everything: 0

model:
  class_path: models.DPModel
  init_args:
    num_users: 943
    num_items: 1682
    embed_dim: 32            # replace with dataset.get_vocab_sizes()['num_items']
    num_genders: 2               # typically 0 (F), 1 (M)
    num_occupations: 21          # number of unique occupation categories
    genre_dim: 19
    mlp_dims:      [128, 64]
    dropout:       0.2
    learning_rate: 1e-3
    l2_penalty:    1e-3
    loss_function: "Huber"
    target_min:    1.0
    target_max:    5.0
    use_attrs:     true
    predict_file: "opacus_strong"  # Name of the file to save predictions

    # DP args
    enable_dp:      true
    target_epsilon: 0.209    # or 1.0, 5.0 for other regimes
    target_delta:   1e-5
    max_grad_norm:  1.0

do_train: true
do_test: true
do_predict: false
do_validate: true
do_analyze: false