seed_everything: 42

model:
  class_path: models.DPFM_GANTrainer
  init_args:
    num_users: 478615
    num_items: 17470
    num_genders: 2
    num_occupations: 21
    genre_dim: 19
    embed_dim: 16
    mlp_dims: [128, 64]
    dropout: 0.2
    loss_function: "MSE"
    learning_rate: 1e-3
    l2_penalty: 1e-5
    target_min: 1.0
    target_max: 5.0
    use_attrs: true
    enable_dp: true
    noise_scale: 0.7          # noise multiplier for DP
    clip_norm: 1.0            # gradient clipping
    delta: 1e-5
    gan_weight: 0.1           # how much the GAN loss contributes
    critic_lr: 1e-4
    generator_lr: 1e-3
    n_critic: 5
    lambda_gp: 10.0           # gradient penalty for WGAN-GP

do_train: false
do_validate: false
do_test: false
do_predict: false
do_attack: true