seed_everything: 42

model:
  class_path: models.WGAN
  init_args:
    noise_dim: 32
    output_dim: 25
    lr: 1e-6
    n_critic: 5
    lambda_gp: 0.5


do_train: false
do_validate: false
do_test: false
do_predict: false
do_attack: true